### ISSUE TITLE
sayhi-mina 项目编译后json文件为空，导致IDE报错

### ISSUE THREAD

**Issue by chyroc** [tinajs/tina-examples#1]

**Comment by chyroc** [comment]
pages/hi.json 为空

**Comment by imyelo** [comment]
感谢反馈～

已经将问题修复并发布 `mina-loader@1.4.2`，请更新项目中依赖的 mina-loader 版本。

问题的原因，是近期 **mina-loader** 的一次更新疏忽了。之前的 mina-loader 在处理空部块时会直接跳过；近期为了使不同部块的处理逻辑更一致，所以统一改为了 **无论有无编写部块都会产生对应的文件**，其中没有考虑到 `.json` 文件无数据时应该输出 `{}`。
另外 tina-examples 使用 `package-lock.json` 锁依赖版本，如果使用 npm 安装依赖，mina-loader 的版本则还停留在 `1.2`，所以直接编译后都没重现过这个问题。

@Chyroc 应该是 yarn 用户吧？可能需要先删除一下本地的 `yarn.lock` 再重新安装一次依赖，或者执行 `yarn upgrade mina-loader`。

**Comment by imyelo** [comment]
问题代码：
https://github.com/tinajs/mina-webpack/commit/112dcbaf662bab88efc1782020e154e4fb9f1bbf#diff-2cfaf44b5c83cd64ab9ccabda23d654bR110
